server.port=8082

bank.api.url=http://localhost:8081
bank.api.port=8081
bank.api.host=localhost
jwt.secret=a-string-secret-at-least-256-bits-long
jwt.expiration=3600000

spring.datasource.url=jdbc:postgresql://localhost:54321/bank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE